enum SemanticColor {
  brandPrimary,
  brandSecondary,
  brandTertiary,
  gradeExcellent,
  gradeVeryGood,
  gradeGood,
  gradeSatisfactory,
  gradeAcceptable,
  gradeFailing,
  statusPresent,
  statusExcused,
  statusUnexcused,
  statusLate,
  statusMixed,
  statusNoData,
}
